# Assuming we use Ubuntu Server 22.04
FROM ubuntu:jammy

# Basic setup
RUN apt-get update -y && apt-get upgrade -y

# Install basic system dependencies
ARG essential_packages="build-essential python3.10 python-is-python3 python3-venv"
RUN apt-get install -y ${essential_packages}

RUN mkdir /ros2_ws
RUN mkdir /ros2_ws/src

WORKDIR /ros2_ws

COPY . /ros2_ws/

WORKDIR /ros2_ws

RUN echo $(python --version)

# RUN make hello

RUN echo $(python --version)
# CMD tail -f /dev/null
