import time
import RPi.GPIO as GPIO

PWM_FREQUENCY = 4096
DEFAULT_PWM_PIN = 23
DEFAULT_DIR_PIN = 18

FILL_GPIO_LEVEL = GPIO.HIGH
EMPTY_GPIO_LEVEL = GPIO.LOW
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(DEFAULT_DIR_PIN, GPIO.OUT)
GPIO.setup(DEFAULT_PWM_PIN, GPIO.OUT)
pwm_output = GPIO.PWM(DEFAULT_PWM_PIN, PWM_FREQUENCY)


# GPIO.output(DEFAULT_DIR_PIN, FILL_GPIO_LEVEL)
GPIO.output(DEFAULT_DIR_PIN, EMPTY_GPIO_LEVEL)

# pwm_output.start(60)

# time.sleep(8)

# pwm_output.stop()
