import time
import RPi.GPIO as GPIO

PWM_FREQUENCY = 1000
DEFAULT_PWM_PIN = 18
DEFAULT_DIR_PIN = 25

FORWARD_LEVEL = GPIO.HIGH
BACKWARD_LEVEL = GPIO.LOW
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(DEFAULT_DIR_PIN, GPIO.OUT)
GPIO.setup(DEFAULT_PWM_PIN, GPIO.OUT)
pwm_output = GPIO.PWM(DEFAULT_PWM_PIN, PWM_FREQUENCY)



# GPIO.output(DEFAULT_DIR_PIN, FORWARD_LEVEL)
GPIO.output(DEFAULT_DIR_PIN, BACKWARD_LEVEL)

pwm_output.start(80)

time.sleep(8)

pwm_output.stop()
