<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>eel_world_sim</name>
  <version>1.2.12</version>
  <description>Simple fake-world simulation for local eel development.</description>
  <maintainer email="foxpoint.se@gmail.com">Foxpoint marinrobotik</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
