from typing import Any

def init(args: list[str] | None = ...) -> None: ...
def spin(node: object, executor: object | None = ...) -> None: ...
def shutdown() -> None: ...
def try_shutdown() -> None: ...
