class ExternalShutdownException(Exception): ...

class MultiThreadedExecutor:
    def __init__(self, num_threads: int | None = ...) -> None: ...
    def add_node(self, node: object) -> None: ...
    def spin(self) -> None: ...
    def shutdown(self, timeout_sec: float = ...) -> None: ...
