from typing import Any

class Node:
    def __init__(
        self,
        node_name: str,
        *,
        context: Any = ...,
        enable_logger_config: bool = ...,
        use_global_arguments: bool = ...,
        start_parameter_services: bool = ...,
        parameter_overrides: Any = ...,
        allow_undeclared_parameters: bool = ...,
        automatically_declare_parameters_from_overrides: bool = ...,
    ) -> None: ...
    def get_logger(self) -> Any: ...
    def create_subscription(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_publisher(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_timer(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_client(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_service(self, *args: Any, **kwargs: Any) -> Any: ...
    def declare_parameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_parameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def destroy_node(self) -> None: ...
