version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

services:
  boat:
    image: foxpoint/eel:jazzy
    command: >
      ros2 launch eel_bringup boat.launch.py
      boat:=alen
      pigpiod_host:=pigpiod
      data_logger:=true
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB4:/dev/ttyUSB4
    volumes:
      - ../../fleet/local_certs_and_config/:/home/ubuntu/fleet/local_certs_and_config/:ro
      - ./cyclonedds.xml:/eel/cyclonedds.xml:ro
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    logging: *default-logging

  ros_bag:
    image: foxpoint/eel:jazzy
    command: bash -c "ros2 bag record --all --storage mcap --output ros_bags/$(date +'%Y-%m-%d_%H-%M-%S')"
    volumes:
      - ../ros_bags/:/eel/ros_bags/:rw
      - ./cyclonedds.xml:/eel/cyclonedds.xml:ro
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    logging: *default-logging
