version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

services:
  imu:
    image: foxpoint/eel:foxy
    command: ros2 run eel imu
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  motor:
    image: foxpoint/eel:foxy
    command: ros2 run eel motor
    privileged: true
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  rudder:
    image: foxpoint/eel:foxy
    command: ros2 run eel rudder --ros-args -p pigpiod_host:=${PIGPIOD_HOST:-pigpiod}
    privileged: true
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  battery:
    image: foxpoint/eel:foxy
    command: ros2 run eel battery
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  pressure:
    image: foxpoint/eel:foxy
    command: ros2 run eel pressure --ros-args -p serial_port:=/dev/ttyUSB0
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  gnss:
    image: foxpoint/eel:foxy
    command: ros2 run eel gnss --ros-args -p serial_port:=/dev/ttyUSB1
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  depth_control:
    image: foxpoint/eel:foxy
    command: ros2 run eel depth_control_rudder
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  modem:
    image: foxpoint/eel:foxy
    command: ros2 run eel modem
    devices:
      - "/dev/ttyUSB4:/dev/ttyUSB4"
    privileged: true
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  mqtt_bridge:
    image: foxpoint/eel:foxy
    command: ros2 run eel mqtt_bridge --ros-args -p path_for_config:=/home/ubuntu/fleet/local_certs_and_config/iot_config.json
    volumes:
      - ../../fleet/local_certs_and_config/:/home/ubuntu/fleet/local_certs_and_config/:r
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    logging: *default-logging

  navigation_action_server:
    image: foxpoint/eel:foxy
    command: ros2 run eel navigate
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  navigation_action_client:
    image: foxpoint/eel:foxy
    command: ros2 run eel navigate_client
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  leakage:
    image: foxpoint/eel:foxy
    command: ros2 run eel leakage
    network_mode: ${NETWORK_MODE:-host}
    privileged: true
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  localization:
    image: foxpoint/eel:foxy
    command: ros2 run eel localization
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  led_node:
    image: foxpoint/eel:foxy
    command: ros2 run eel led_control
    network_mode: ${NETWORK_MODE:-bridge}
    privileged: true
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  data_logger:
    image: foxpoint/eel:foxy
    command: ros2 run eel data_logger
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    logging: *default-logging

  ros_bag:
    image: foxpoint/eel:foxy
    command: bash -c "ros2 bag record --all --storage mcap --output ros_bags/$(date +'%Y-%m-%d_%H-%M-%S')"
    volumes:
      - ../ros_bags/:/eel/ros_bags/:rw
      - ./cyclonedds.xml:/eel/cyclonedds.xml:r
    network_mode: ${NETWORK_MODE:-host}
    environment:
      CYCLONEDDS_URI: file:///eel/cyclonedds.xml
    logging: *default-logging
