from typing import Generic, TypeVar

GoalT = TypeVar("GoalT")
ResultT = TypeVar("ResultT")
FeedbackT = TypeVar("FeedbackT")
ImplT = TypeVar("ImplT")

class ServerGoalHandle(Generic[GoalT, ResultT, FeedbackT, ImplT]):
    request: GoalT
    def execute(self) -> None: ...
    def publish_feedback(self, feedback: FeedbackT) -> None: ...
    @property
    def is_cancel_requested(self) -> bool: ...
    def succeed(self) -> None: ...
    def canceled(self) -> None: ...
