from typing import Any

class Logger:
    def info(self, message: str, *args: Any, **kwargs: Any) -> bool: ...
    def debug(self, message: str, *args: Any, **kwargs: Any) -> bool: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> bool: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> bool: ...

def get_logger(name: str) -> Logger: ...
